import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'sv' | 'so';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.cart': 'Cart',
    'header.language': 'Language',
    
    // Navigation
    'nav.home': 'Home',
    'nav.benefits': 'Benefits',
    'nav.product': 'The Treatment',
    'nav.influencers': 'Influencers',
    'nav.tutorials': 'Tutorials',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    
    // Hero
    'hero.badge': 'LIMITED MONTHLY SUPPLY • ORGANIC PRODUCTS',
    'hero.title': 'Your Hair, Perfected with Smart Personalized Solutions',
    'hero.subtitle': 'Experience AI-powered hair analysis combined with expert human guidance. Get organic products tailored specifically for your unique hair texture and goals.',
    'hero.cta': 'Start Your Transformation',
    'hero.viewPricing': 'View Pricing',
    
    // Trust Indicators
    'trust.safePregnancy': 'Safe for Pregnancy',
    'trust.organic': '100% Organic',
    'trust.noHeat': 'No Heat Required',
    'trust.lasts': 'Lasts 3-6 Months',
    
    // Problem/Solution
    'problem.title': 'Why Traditional Keratin Fails',
    'problem.subtitle': 'The Problem with Regular Treatments',
    'problem.text1': "We can all agree it's beautiful in the beginning. After a couple of weeks, you start losing hair because the treatment made your hair straight. And it's because your hair is trying to stretch back.",
    'problem.text2': "After 2-3 months, you end up with 2 different hair textures. Some even notice the new growing hair has a dryer texture. Traditional keratin needs heat and hair straightening, and it's not recommended for pregnancy or kids. Once you've had that treatment, I normally don't suggest mine until your natural hair has grown out all the way to your shoulders.",
    'solution.title': 'The Quality Hair Solution',
    'solution.subtitle': 'Organic Keratin That Works With Your Curls',
    'solution.text': 'Our treatment penetrates your hair shaft without breaking bonds. Your curls stay - they just become healthier, more defined, and manageable. No formaldehyde, no heat damage, safe for everyone.',
    
    // Pricing
    'pricing.title': 'Choose Your Treatment Size',
    'pricing.subtitle': 'Price based on hair length and thickness',
    'pricing.addToCart': 'Add to Cart',
    'pricing.popular': 'Most Popular',
    'pricing.short': 'Short Hair',
    'pricing.medium': 'Medium Hair',
    'pricing.long': 'Long Hair',
    'pricing.extraLong': 'Extra Long',
    'pricing.consultation': 'Not Sure? Book a Consultation',
    'pricing.consultationDesc': 'Get personalized advice from our hair experts',
    'pricing.bookCall': 'Book Free Call',
    
    // How It Works
    'steps.title': 'Your Journey to Better Hair',
    'steps.step1.title': 'Select Hair Type',
    'steps.step1.desc': 'Tell us about your hair - curly, straight, frizzy, or afro texture',
    'steps.step2.title': 'Upload Photos',
    'steps.step2.desc': "Share clear images so our advisors can understand your hair's unique needs",
    'steps.step3.title': 'Get Your Products',
    'steps.step3.desc': 'Receive curated recommendations with detailed usage instructions and checkout',
    
    // Benefits
    'benefits.title': 'Why Choose Quality Hair?',
    'benefits.maintains': 'Maintains Curl Pattern',
    'benefits.maintainsDesc': 'Your natural curls stay intact - just healthier and more defined',
    'benefits.organic': '100% Organic Formula',
    'benefits.organicDesc': 'No formaldehyde, no harsh chemicals - safe for pregnancy and kids',
    'benefits.noHeat': 'No Heat Required',
    'benefits.noHeatDesc': 'Unlike traditional keratin, no flat iron or blow dryer needed',
    'benefits.lasting': 'Long-Lasting Results',
    'benefits.lastingDesc': '3-6 months of beautiful, manageable hair',
    
    // Comparison
    'comparison.title': 'How We Compare',
    'comparison.us': 'Quality Hair',
    'comparison.traditional': 'Traditional Keratin',
    'comparison.maintainsCurls': 'Maintains Curls',
    'comparison.chemicalFree': 'Chemical Free',
    'comparison.pregnancySafe': 'Pregnancy Safe',
    'comparison.noHeat': 'No Heat Required',
    
    // Social Proof
    'social.title': 'Featured By Top Influencers',
    'social.subtitle': "Trusted by thousands and celebrated by social media's biggest voices",
    'social.followers': 'Followers',
    'social.watch': 'Watch Video',
    'social.stats.customers': 'Happy Customers',
    'social.stats.influencers': 'Influencer Partners',
    'social.stats.views': 'Social Media Views',
    
    // Testimonials
    'testimonials.title': 'Real Results from Real People',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.all': 'All',
    'faq.treatment': 'Treatment',
    'faq.safety': 'Safety',
    'faq.aftercare': 'Aftercare',
    'faq.ordering': 'Ordering',
    
    // About
    'about.title': 'Our Story',
    'about.subtitle': 'Founded by someone who understands your hair journey',
    
    // Final CTA
    'final.title': 'Ready to Transform Your Hair?',
    'final.subtitle': "Join thousands who've discovered their perfect organic hair care routine. Limited supply available this month.",
    'final.cta': 'Start Your Journey Now',
    
    // Footer
    'footer.rights': 'All rights reserved',
    'footer.quickLinks': 'Quick Links',
    'footer.support': 'Support',
    'footer.connect': 'Connect',
    
    // Hair Types
    'hairtype.curly': 'Curly',
    'hairtype.straight': 'Straight',
    'hairtype.frizzy': 'Frizzy',
    'hairtype.afro': 'Afro',
    
    // Common
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.viewAll': 'View All',
    'common.close': 'Close',
    
    // Benefits Section (expanded)
    'benefits.subtitle': 'Experience the transformation your hair deserves',
    'benefits.qualityHair': 'Quality Hair',
    'benefits.qualityHairDesc': 'Achieve healthy, radiant hair defined by its vitality and strength',
    'benefits.maintainsCurl': 'Maintains Your Curl Pattern',
    'benefits.maintainsCurlDesc': 'Keep your natural texture while enhancing definition and hydration',
    'benefits.manageability': 'Manageability',
    'benefits.manageabilityDesc': 'Easy detangling, smooth styling, and effortless daily care',
    'benefits.lessBreakage': 'Less Hair Fall & Breakage',
    'benefits.lessBreakageDesc': 'Strengthen from within to reduce shedding and protect against damage',
    'benefits.growthSupport': 'Growth Support',
    'benefits.growthSupportDesc': 'Create the perfect foundation for healthy, sustained hair growth',
    'benefits.heatFree': 'Heat-Free Treatment',
    'benefits.heatFreeDesc': 'No heat, no flat irons, no damage — just natural balance',
    
    // Pricing Section (expanded)
    'pricing.mostPopular': 'MOST POPULAR',
    'pricing.minimal': 'Minimal',
    'pricing.minimalDesc': 'Fine, short hair - Under shoulder length',
    'pricing.moderate': 'Moderate',
    'pricing.moderateDesc': 'Medium thickness - Shoulder-length hair',
    'pricing.full': 'Full',
    'pricing.fullDesc': 'Thick, long hair - Below shoulder/above chest',
    'pricing.maximum': 'Maximum',
    'pricing.maximumDesc': 'Very thick hair - Below chest length',
    'pricing.feature.completeKit': 'Complete kit',
    'pricing.feature.applicationGuide': 'Application guide',
    'pricing.feature.videoSupport': 'Video support',
    'pricing.feature.lasts': 'Lasts 3-6 months',
    'pricing.addons': 'Add-On Products',
    'pricing.bundle': 'Hair Mask + Serum Bundle',
    'pricing.bundleDesc': 'Bundle both for optimal aftercare',
    'pricing.maskOnly': 'Hair Mask Only',
    'pricing.maskOnlyDesc': 'Deep conditioning treatment',
    'pricing.serumOnly': 'Hair Serum Only',
    'pricing.serumOnlyDesc': 'Daily shine and protection',
    'pricing.notSure': 'Not Sure Which Size?',
    'pricing.consultationText': "Book a 10-minute video consultation for €10. We'll assess your hair and recommend the perfect amount. If you purchase during the call, the €10 is credited toward your order. Otherwise, the consultation fee is non-refundable.",
    'pricing.bookConsultation': 'Book Consultation (€10)',
    'pricing.sessionTitle': '30-Minute Session',
    'pricing.sessionDesc': 'Personal video call with our hair expert',
    'pricing.planTitle': 'Personalized Plan',
    'pricing.planDesc': 'Custom treatment recommendations for your hair',
    'pricing.creditTitle': 'Credit Toward Purchase',
    'pricing.creditDesc': '€10 consultation fee applied to your order',
    
    // FAQ Section (expanded)
    'faq.subtitle': 'Everything you need to know about our organic keratin treatment',
    'faq.allQuestions': 'All Questions',
    'faq.stillQuestions': 'Still have questions?',
    'faq.contactSupport': 'Contact our support team →',
    'faq.q1': 'Will this straighten my hair?',
    'faq.a1': 'NO - this is what makes us unique. Your curls stay, they just become healthier, more defined, and manageable. In the first few weeks, curls may appear looser due to added moisture, but they return to their natural pattern.',
    'faq.q2': 'How long does the treatment last?',
    'faq.a2': "3-6 months depending on your hair type and aftercare. Unlike traditional treatments, there's no harsh demarcation line - it fades naturally.",
    'faq.q3': 'How is this different from salon keratin treatments?',
    'faq.a3': 'Traditional salon keratin uses heat and chemicals to break down hair bonds and straighten. Our organic formula works WITH your natural curl pattern, adding strength and reducing frizz without altering your texture.',
    'faq.q4': 'Is it safe for children and pregnancy?',
    'faq.a4': 'Yes! 100% organic with molecules naturally found in hair. No formaldehyde, no harmful chemicals. Safe for all ages and pregnancy.',
    'faq.q5': 'What ingredients are in the treatment?',
    'faq.a5': 'Our formula contains organic keratin proteins, natural amino acids, argan oil, and plant-based conditioning agents. Zero formaldehyde, parabens, or sulfates.',
    'faq.q6': 'Can I use it on color-treated hair?',
    'faq.a6': "Absolutely! Our treatment is safe for all hair types including color-treated, highlighted, and chemically processed hair. It may even help extend your color's vibrancy.",
    'faq.q7': 'How often can I repeat the treatment?',
    'faq.a7': "Wait 3-4 months between treatments (sometimes 5-6 months). Your hair will tell you when it needs more - too much protein isn't recommended.",
    'faq.q8': 'What shampoo should I use after treatment?',
    'faq.a8': 'Use a sulfate-free shampoo to maximize results. We recommend waiting 48 hours before the first wash. Any gentle, sulfate-free shampoo works well.',
    'faq.q9': 'Can I swim or exercise after treatment?',
    'faq.a9': "Wait 48-72 hours before swimming or heavy sweating. After that, you're good to go! Rinse hair with fresh water after swimming in chlorinated or salt water.",
    'faq.q10': "What's included with my purchase?",
    'faq.a10': '• Your organic keratin treatment (size selected)\n• Detailed application guide\n• Access to video tutorials\n• Email support\n• 30-day satisfaction guarantee',
    'faq.q11': 'How do I choose the right size?',
    'faq.a11': 'Use our Hair Analysis tool for a personalized recommendation. Generally: Minimal (short/fine hair), Moderate (shoulder-length), Full (long/thick), Maximum (very long/very thick).',
    'faq.q12': 'What is your return policy?',
    'faq.a12': "We offer a 30-day satisfaction guarantee. If you're not happy with your results, contact us for a full refund or exchange. Unopened products can be returned within 60 days.",
    
    // How It Works Section
    'howItWorks.title': 'Three Simple Steps',
    'howItWorks.subtitle': 'Easy application process - no salon required',
    'howItWorks.clickInstruction': 'Click on each step for detailed guidance (tap on mobile)',
    'howItWorks.footer': '*Full application guide provided with purchase',
    'howItWorks.step1.title': 'Apply',
    'howItWorks.step1.short': 'Wash with shampoo only • Dry completely • Apply section by section',
    'howItWorks.step1.intro': 'You are able to book 30 min video call for guiding or read the script for applying',
    'howItWorks.step1.d1': 'Have a towel ready',
    'howItWorks.step1.d2': '2-3 different hair combs different size & gloves',
    'howItWorks.step1.d3': 'Wash your hair only with shampoo',
    'howItWorks.step1.d4': "Before applying your hair needs to be 100% dry and no traces of Oil. Even wait 1 more day to be sure",
    'howItWorks.step1.d5': 'Hair type 1A - 3B your hair can airdry before applying make sure you comb it out properly',
    'howItWorks.step1.d6': "Hair type 3C-4C you are able to blowdry your hair flat if it's easier to manage it like that",
    'howItWorks.step1.d7': 'Split your hair to 10-12 layers. Left side 5-6 layers and right side same. Start from the bottom',
    'howItWorks.step1.d8': 'Brush it out first properly',
    'howItWorks.step1.d9': "Apply a small amount of the treatment and brush it with a small comb 5-6 times til you feel it's easier to comb and the treatment is in properly",
    'howItWorks.step1.d10': 'Now you are able to apply more protein on that side again',
    'howItWorks.step1.d11': 'And move to the next side',
    'howItWorks.step1.d12': "Make sure you don't apply the treatment on your scalp or massage it in to your scalp or your babyhair yet. But try go as near as you can",
    'howItWorks.step1.d13': 'Your time starts from when you have applied the whole treatment on your hair',
    'howItWorks.step1.d14': 'Hair type 1A - 3A - can have it in for 60-80 minutes',
    'howItWorks.step1.d15': 'Hair type 3B-4A - can have it in for 2 hours',
    'howItWorks.step1.d16': '4B-4C can have it in for 2 hours and 30 min',
    'howItWorks.step1.d17': 'When you got 20 min left before washing your hair - you are able to tap your scalp so it reach the scalp and apply it on your babyhair',
    'howItWorks.step1.d18': 'If it feels itchy don\'t scratch. It will disappear. (Reason of the itchy is dry skin)',
    'howItWorks.step1.helpText': 'Need help applying?',
    'howItWorks.step1.bookCall': 'Book a video guidance call',
    'howItWorks.step2.title': 'Rinse',
    'howItWorks.step2.short': 'Pure water only • No shampoo or conditioner • Let air dry naturally',
    'howItWorks.step2.intro': "Rinse it only with water take a full bath. Make sure it's 100% out of the hair",
    'howItWorks.step2.d1': "Rinse it only with water take a full bath. Make sure it's 100% out of the hair",
    'howItWorks.step2.d2': 'Hair type 1A - 3B let your hair fully AIR DRY',
    'howItWorks.step2.d3': '3C - 4C make one braid and let it airdry like that',
    'howItWorks.step2.d4': "Don't use any oils or creams after. Even if your hair feels dry afterwards",
    'howItWorks.step3.title': 'Maintain',
    'howItWorks.step3.short': 'First wash after 4-7 days (mask only) • Use sulfate-free products • Enjoy healthier hair for months',
    'howItWorks.step3.intro': 'After 4-7 days you are able to wash your hair again but only with a hairmask',
    'howItWorks.step3.d1': 'After 4-7 days you are able to wash your hair again but only with a hairmask',
    'howItWorks.step3.d2': '(sulphate free is our recommendation)',
    'howItWorks.step3.d3': 'And if you got the chance to try out the one I got. Make sure it stays in your hair 1h up to 2h rinse it out',
    'howItWorks.step3.d4': 'Now you are able to use oils and also style your hair with blowdry',
    'howItWorks.step3.d5': 'Third wash?',
    'howItWorks.step3.d6': 'You can use shampoo and conditioner',
    'howItWorks.step3.d7': 'I recommend sulphate free',
    
    // Comparison Section
    'comparison.subtitle': 'Not just another keratin treatment - a revolutionary approach to hair care',
    'comparison.ourTreatment': 'Our Organic Treatment',
    'comparison.trad.straightens': 'Straightens & flattens hair',
    'comparison.ours.maintains': 'Maintains natural texture',
    'comparison.trad.heat': 'Requires heat & flat iron',
    'comparison.ours.noHeat': 'No heat needed',
    'comparison.trad.formaldehyde': 'Contains formaldehyde',
    'comparison.ours.organic': '100% organic formula',
    'comparison.trad.damages': 'Damages curl pattern',
    'comparison.ours.enhances': 'Enhances curl definition',
    'comparison.trad.notSafe': 'Not safe for pregnancy',
    'comparison.ours.safe': 'Safe for pregnancy & kids',
    'comparison.trad.demarcation': 'Harsh demarcation line',
    'comparison.ours.seamless': 'Natural, seamless grow-out',
    'comparison.trad.drier': 'Hair gets drier over time',
    'comparison.ours.improves': 'Progressive improvement',
    
    // About Section
    'about.discoverSubtitle': 'Discover the passion and dedication behind Quality Hair',
    'about.tapInstruction': 'Click on each card to read the full story',
    'about.readMore': 'Tap to read more...',
    'about.journey.title': 'MY JOURNEY',
    'about.journey.text': "Quality Hair started from my own struggle with damaged, lifeless hair.\n\nFor years, I used hair dyes that dried out my hair. I had to forget about hair growth.\n\nI tried everything out there — nothing worked.\n\nThen one day, I found a keratin product at a market that changed everything.\n\nAfter just 7 months, my hair became healthy, longer, and easier to manage.\n\nI managed to convince my stylist to sell the product.\n\nOne year later, she agreed.\n\nI started presenting the treatment to friends, family members, and even strangers I met.\nI performed it on them, and when they came back for a second treatment, a bell rang in my head.\n\nI gained a client base that spread quite quickly.\n\nWhat started as a hobby took me by storm.\nI wanted to prove that my treatment was different — no heat, no harsh chemicals, just real results. And when my clients started coming back months later, I knew I had something special.",
    'about.creator.title': 'THE CREATOR',
    'about.creator.text': "I built this entire operation myself.\nNo funding. No investors. No team.\nI chose the countries. I did the marketing. I handled bookings/deposits.\nI met clients worldwide.\nI did the work.\nThis is more than business –\n\nToday, I've reached a point where demand is so high,\nthat flying like I do is no longer sustainable",
    'about.mission.title': 'OUR MISSION',
    'about.mission.text': "I always say: good hair is defined by health, not texture.\nMy treatment works for kids, for pregnant women, and for anyone who wants to love their hair without changing it.\nIt brings moisture, reduces breakage, and restores curls — all without heat or damage.\nAt the end of the day, I want to remind women that beauty doesn't mean straightening your identity. It means taking care of what's already you.",
    'about.stats.customers': 'Happy Customers',
    'about.stats.natural': 'Natural Ingredients',
    'about.stats.experience': 'Years Experience',
    
    // Results Gallery Section
    'results.title': 'Before & After Transformations',
    'results.subtitle': 'See the incredible results our clients have achieved with our organic keratin treatments. Natural curls enhanced, not changed.',
    'results.before': 'Before',
    'results.after': 'Results',
    
    // Footer Section
    'footer.learnMore': 'Learn More',
    'footer.howItWorks': 'How It Works',
    'footer.pricing': 'Pricing',
    'footer.faq': 'FAQ',
    'footer.testimonials': 'Testimonials',
    'footer.benefits': 'Benefits',
    'footer.compareTreatments': 'Compare Treatments',
    'footer.ourStory': 'Our Story',
    'footer.resultsGallery': 'Results Gallery',
    'footer.contactWhatsApp': 'Contact via WhatsApp',
    'footer.emailUs': 'Email Us',
    'footer.bookConsultation': 'Book Consultation',
    'footer.instagram': 'Instagram',
    'footer.tiktok': 'TikTok',
    'footer.snapchat': 'Snapchat',
    'footer.organicCertified': '✓ 100% Organic Certified',
    'footer.safePregnancy': '✓ Safe for Pregnancy',
    'footer.noHeatDamage': '✓ No Heat Damage',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    
    // Final CTA
    'final.getRecommendation': 'Get Personalized Recommendation',
    'final.viewAllPricing': 'View All Pricing',
    'final.limitedSupply': 'Limited monthly supply available.',
  },
  sv: {
    // Header
    'header.cart': 'Varukorg',
    'header.language': 'Språk',
    
    // Navigation
    'nav.home': 'Hem',
    'nav.benefits': 'Fördelar',
    'nav.product': 'Behandlingen',
    'nav.influencers': 'Influencers',
    'nav.tutorials': 'Handledningar',
    'nav.pricing': 'Priser',
    'nav.faq': 'FAQ',
    
    // Hero
    'hero.badge': 'BEGRÄNSAD MÅNADSLEVERANS • EKOLOGISKA PRODUKTER',
    'hero.title': 'Ditt Hår, Perfektionerat med Smarta Personliga Lösningar',
    'hero.subtitle': 'Upplev AI-driven håranalys kombinerad med expertvägledning. Få ekologiska produkter skräddarsydda specifikt för din unika hårstruktur och mål.',
    'hero.cta': 'Börja Din Transformation',
    'hero.viewPricing': 'Se Priser',
    
    // Trust Indicators
    'trust.safePregnancy': 'Säkert vid Graviditet',
    'trust.organic': '100% Ekologiskt',
    'trust.noHeat': 'Ingen Värme Krävs',
    'trust.lasts': 'Varar 3-6 Månader',
    
    // Problem/Solution
    'problem.title': 'Varför Traditionell Keratin Misslyckas',
    'problem.subtitle': 'Problemet med Vanliga Behandlingar',
    'problem.text1': 'Vi kan alla hålla med om att det är vackert i början. Efter ett par veckor börjar du tappa hår eftersom behandlingen gjorde ditt hår rakt. Och det beror på att ditt hår försöker sträcka sig tillbaka.',
    'problem.text2': 'Efter 2-3 månader får du 2 olika hårstrukturer. Vissa märker till och med att det nya växande håret har en torrare struktur. Traditionell keratin behöver värme och hårplattning, och det rekommenderas inte för graviditet eller barn.',
    'solution.title': 'Quality Hair Lösningen',
    'solution.subtitle': 'Ekologisk Keratin Som Fungerar Med Dina Lockar',
    'solution.text': 'Vår behandling tränger in i din hårstråle utan att bryta bindningar. Dina lockar stannar - de blir bara hälsosammare, mer definierade och hanterbara. Ingen formaldehyd, inga värmeskador, säker för alla.',
    
    // Pricing
    'pricing.title': 'Välj Din Behandlingsstorlek',
    'pricing.subtitle': 'Pris baserat på hårlängd och tjocklek',
    'pricing.addToCart': 'Lägg i Varukorg',
    'pricing.popular': 'Mest Populär',
    'pricing.short': 'Kort Hår',
    'pricing.medium': 'Medellångt Hår',
    'pricing.long': 'Långt Hår',
    'pricing.extraLong': 'Extra Långt',
    'pricing.consultation': 'Osäker? Boka en Konsultation',
    'pricing.consultationDesc': 'Få personlig rådgivning från våra hårexperter',
    'pricing.bookCall': 'Boka Gratis Samtal',
    
    // How It Works
    'steps.title': 'Din Resa Till Bättre Hår',
    'steps.step1.title': 'Välj Hårtyp',
    'steps.step1.desc': 'Berätta om ditt hår - lockigt, rakt, frissigt eller afro-struktur',
    'steps.step2.title': 'Ladda Upp Foton',
    'steps.step2.desc': 'Dela tydliga bilder så att våra rådgivare kan förstå ditt hårs unika behov',
    'steps.step3.title': 'Få Dina Produkter',
    'steps.step3.desc': 'Ta emot kurerade rekommendationer med detaljerade användningsinstruktioner',
    
    // Benefits
    'benefits.title': 'Varför Välja Quality Hair?',
    'benefits.maintains': 'Bevarar Lockmönster',
    'benefits.maintainsDesc': 'Dina naturliga lockar förblir intakta - bara hälsosammare och mer definierade',
    'benefits.organic': '100% Ekologisk Formel',
    'benefits.organicDesc': 'Ingen formaldehyd, inga hårda kemikalier - säkert för graviditet och barn',
    'benefits.noHeat': 'Ingen Värme Krävs',
    'benefits.noHeatDesc': 'Till skillnad från traditionell keratin behövs ingen plattång eller hårtork',
    'benefits.lasting': 'Långvariga Resultat',
    'benefits.lastingDesc': '3-6 månader av vackert, hanterbart hår',
    
    // Comparison
    'comparison.title': 'Hur Vi Jämför',
    'comparison.us': 'Quality Hair',
    'comparison.traditional': 'Traditionell Keratin',
    'comparison.maintainsCurls': 'Bevarar Lockar',
    'comparison.chemicalFree': 'Kemikaliefri',
    'comparison.pregnancySafe': 'Graviditetssäker',
    'comparison.noHeat': 'Ingen Värme Krävs',
    
    // Social Proof
    'social.title': 'Presenterad av Toppinfluenser',
    'social.subtitle': 'Pålitlig av tusentals och hyllad av sociala mediers största röster',
    'social.followers': 'Följare',
    'social.watch': 'Se Video',
    'social.stats.customers': 'Nöjda Kunder',
    'social.stats.influencers': 'Influencer-Partners',
    'social.stats.views': 'Visningar på Sociala Medier',
    
    // Testimonials
    'testimonials.title': 'Verkliga Resultat från Verkliga Människor',
    
    // FAQ
    'faq.title': 'Vanliga Frågor',
    'faq.all': 'Alla',
    'faq.treatment': 'Behandling',
    'faq.safety': 'Säkerhet',
    'faq.aftercare': 'Eftervård',
    'faq.ordering': 'Beställning',
    
    // About
    'about.title': 'Vår Berättelse',
    'about.subtitle': 'Grundad av någon som förstår din hårresa',
    
    // Final CTA
    'final.title': 'Redo Att Transformera Ditt Hår?',
    'final.subtitle': 'Gå med tusentals som har upptäckt sin perfekta ekologiska hårvårdsrutin. Begränsat lager tillgängligt denna månad.',
    'final.cta': 'Börja Din Resa Nu',
    
    // Footer
    'footer.rights': 'Alla rättigheter förbehållna',
    'footer.quickLinks': 'Snabblänkar',
    'footer.support': 'Support',
    'footer.connect': 'Kontakt',
    
    // Hair Types
    'hairtype.curly': 'Lockigt',
    'hairtype.straight': 'Rakt',
    'hairtype.frizzy': 'Frissigt',
    'hairtype.afro': 'Afro',
    
    // Common
    'common.learnMore': 'Läs Mer',
    'common.getStarted': 'Kom Igång',
    'common.viewAll': 'Visa Alla',
    'common.close': 'Stäng',
    
    // Benefits Section (expanded)
    'benefits.subtitle': 'Upplev den transformation ditt hår förtjänar',
    'benefits.qualityHair': 'Quality Hair',
    'benefits.qualityHairDesc': 'Uppnå friskt, strålande hår definierat av dess vitalitet och styrka',
    'benefits.maintainsCurl': 'Bevarar Ditt Lockmönster',
    'benefits.maintainsCurlDesc': 'Behåll din naturliga textur medan du förbättrar definition och återfuktning',
    'benefits.manageability': 'Hanterbarhet',
    'benefits.manageabilityDesc': 'Enkel utkamning, smidig styling och enkel daglig vård',
    'benefits.lessBreakage': 'Mindre Håravfall & Brott',
    'benefits.lessBreakageDesc': 'Stärk inifrån för att minska håravfall och skydda mot skador',
    'benefits.growthSupport': 'Tillväxtstöd',
    'benefits.growthSupportDesc': 'Skapa den perfekta grunden för hälsosam, långvarig hårtillväxt',
    'benefits.heatFree': 'Värme-fri Behandling',
    'benefits.heatFreeDesc': 'Ingen värme, inga plattänger, inga skador — bara naturlig balans',
    
    // Pricing Section (expanded)
    'pricing.mostPopular': 'MEST POPULÄR',
    'pricing.minimal': 'Minimal',
    'pricing.minimalDesc': 'Fint, kort hår - Under axellängd',
    'pricing.moderate': 'Moderat',
    'pricing.moderateDesc': 'Medeltjockt - Axellångt hår',
    'pricing.full': 'Full',
    'pricing.fullDesc': 'Tjockt, långt hår - Under axlarna/ovanför bröstet',
    'pricing.maximum': 'Maximum',
    'pricing.maximumDesc': 'Mycket tjockt hår - Under brösthöjd',
    'pricing.feature.completeKit': 'Komplett kit',
    'pricing.feature.applicationGuide': 'Applikationsguide',
    'pricing.feature.videoSupport': 'Videostöd',
    'pricing.feature.lasts': 'Varar 3-6 månader',
    'pricing.addons': 'Tilläggsprodukter',
    'pricing.bundle': 'Hårmask + Serum Paket',
    'pricing.bundleDesc': 'Kombinera båda för optimal eftervård',
    'pricing.maskOnly': 'Endast Hårmask',
    'pricing.maskOnlyDesc': 'Djupverkande behandling',
    'pricing.serumOnly': 'Endast Hårserum',
    'pricing.serumOnlyDesc': 'Daglig glans och skydd',
    'pricing.notSure': 'Osäker på Vilken Storlek?',
    'pricing.consultationText': 'Boka en 10-minuters videokonsultation för €10. Vi bedömer ditt hår och rekommenderar rätt mängd. Om du köper under samtalet krediteras €10 mot din order. Annars är konsultationsavgiften ej återbetalbar.',
    'pricing.bookConsultation': 'Boka Konsultation (€10)',
    'pricing.sessionTitle': '30-Minuters Session',
    'pricing.sessionDesc': 'Personligt videosamtal med vår hårexpert',
    'pricing.planTitle': 'Personlig Plan',
    'pricing.planDesc': 'Skräddarsydda behandlingsrekommendationer för ditt hår',
    'pricing.creditTitle': 'Kredit Mot Köp',
    'pricing.creditDesc': '€10 konsultationsavgift appliceras på din order',
    
    // FAQ Section (expanded)
    'faq.subtitle': 'Allt du behöver veta om vår ekologiska keratinbehandling',
    'faq.allQuestions': 'Alla Frågor',
    'faq.stillQuestions': 'Har du fortfarande frågor?',
    'faq.contactSupport': 'Kontakta vårt supportteam →',
    'faq.q1': 'Kommer detta att räta ut mitt hår?',
    'faq.a1': 'NEJ - det är det som gör oss unika. Dina lockar stannar, de blir bara friskare, mer definierade och hanterbara. De första veckorna kan lockar verka lösare på grund av ökad fukt, men de återgår till sitt naturliga mönster.',
    'faq.q2': 'Hur länge varar behandlingen?',
    'faq.a2': '3-6 månader beroende på din hårtyp och eftervård. Till skillnad från traditionella behandlingar finns det ingen hård demarkationslinje - den bleknar naturligt.',
    'faq.q3': 'Hur skiljer sig detta från salongskeratinbehandlingar?',
    'faq.a3': 'Traditionell salongskeratin använder värme och kemikalier för att bryta ner hårbindningar och räta ut. Vår ekologiska formel arbetar MED ditt naturliga lockmönster, lägger till styrka och minskar frizz utan att ändra din textur.',
    'faq.q4': 'Är det säkert för barn och graviditet?',
    'faq.a4': 'Ja! 100% ekologiskt med molekyler som naturligt finns i hår. Ingen formaldehyd, inga skadliga kemikalier. Säkert för alla åldrar och graviditet.',
    'faq.q5': 'Vilka ingredienser finns i behandlingen?',
    'faq.a5': 'Vår formel innehåller ekologiska keratinproteiner, naturliga aminosyror, arganolja och växtbaserade balsam. Noll formaldehyd, parabener eller sulfater.',
    'faq.q6': 'Kan jag använda det på färgat hår?',
    'faq.a6': 'Absolut! Vår behandling är säker för alla hårtyper inklusive färgat, slingat och kemiskt behandlat hår. Den kan till och med hjälpa till att förlänga din färgs livlighet.',
    'faq.q7': 'Hur ofta kan jag upprepa behandlingen?',
    'faq.a7': 'Vänta 3-4 månader mellan behandlingar (ibland 5-6 månader). Ditt hår kommer att tala om för dig när det behöver mer - för mycket protein rekommenderas inte.',
    'faq.q8': 'Vilket schampo ska jag använda efter behandlingen?',
    'faq.a8': 'Använd ett sulfatfritt schampo för att maximera resultaten. Vi rekommenderar att vänta 48 timmar innan första tvätten. Alla milda, sulfatfria schampon fungerar bra.',
    'faq.q9': 'Kan jag simma eller träna efter behandlingen?',
    'faq.a9': 'Vänta 48-72 timmar innan du simmar eller svettas mycket. Efter det är du redo! Skölj håret med sötvatten efter simning i klorerat eller saltvatten.',
    'faq.q10': 'Vad ingår i mitt köp?',
    'faq.a10': '• Din ekologiska keratinbehandling (vald storlek)\n• Detaljerad applikationsguide\n• Tillgång till videohandledningar\n• E-postsupport\n• 30 dagars nöjdhetsgaranti',
    'faq.q11': 'Hur väljer jag rätt storlek?',
    'faq.a11': 'Använd vårt håranalysverktyg för en personlig rekommendation. Generellt: Minimal (kort/fint hår), Moderat (axellångt), Full (långt/tjockt), Maximum (mycket långt/mycket tjockt).',
    'faq.q12': 'Vad är er returpolicy?',
    'faq.a12': 'Vi erbjuder 30 dagars nöjdhetsgaranti. Om du inte är nöjd med dina resultat, kontakta oss för full återbetalning eller byte. Oöppnade produkter kan returneras inom 60 dagar.',
    
    // How It Works Section
    'howItWorks.title': 'Tre Enkla Steg',
    'howItWorks.subtitle': 'Enkel appliceringsprocess - ingen salong krävs',
    'howItWorks.clickInstruction': 'Klicka på varje steg för detaljerad vägledning (tryck på mobil)',
    'howItWorks.footer': '*Komplett applikationsguide medföljer vid köp',
    'howItWorks.step1.title': 'Applicera',
    'howItWorks.step1.short': 'Tvätta med endast schampo • Torka helt • Applicera sektion för sektion',
    'howItWorks.step1.intro': 'Du kan boka ett 30 min videosamtal för vägledning eller läsa manualen för applicering',
    'howItWorks.step1.d1': 'Ha en handduk redo',
    'howItWorks.step1.d2': '2-3 olika hårkammar i olika storlekar & handskar',
    'howItWorks.step1.d3': 'Tvätta håret endast med schampo',
    'howItWorks.step1.d4': 'Innan applicering måste håret vara 100% torrt utan spår av olja. Vänta gärna en dag till för säkerhets skull',
    'howItWorks.step1.d5': 'Hårtyp 1A - 3B ditt hår kan lufttorka innan applicering, se till att kamma ut det ordentligt',
    'howItWorks.step1.d6': 'Hårtyp 3C-4C du kan föna håret platt om det är lättare att hantera det så',
    'howItWorks.step1.d7': 'Dela upp håret i 10-12 lager. Vänster sida 5-6 lager och höger sida samma. Börja nerifrån',
    'howItWorks.step1.d8': 'Borsta ut det ordentligt först',
    'howItWorks.step1.d9': 'Applicera en liten mängd behandling och borsta med en liten kam 5-6 gånger tills det känns lättare att kamma och behandlingen är ordentligt inne',
    'howItWorks.step1.d10': 'Nu kan du applicera mer protein på den sidan igen',
    'howItWorks.step1.d11': 'Och flytta till nästa sida',
    'howItWorks.step1.d12': 'Se till att du inte applicerar behandlingen på hårbotten eller masserar in den i hårbotten eller ditt babyhår ännu. Men försök komma så nära du kan',
    'howItWorks.step1.d13': 'Din tid börjar från när du har applicerat hela behandlingen på ditt hår',
    'howItWorks.step1.d14': 'Hårtyp 1A - 3A - kan ha den i 60-80 minuter',
    'howItWorks.step1.d15': 'Hårtyp 3B-4A - kan ha den i 2 timmar',
    'howItWorks.step1.d16': '4B-4C kan ha den i 2 timmar och 30 min',
    'howItWorks.step1.d17': 'När du har 20 min kvar innan du tvättar håret - kan du klappa på hårbotten så det når hårbotten och applicera på ditt babyhår',
    'howItWorks.step1.d18': 'Om det känns kliande, klia inte. Det försvinner. (Orsaken till klådan är torr hud)',
    'howItWorks.step1.helpText': 'Behöver du hjälp med appliceringen?',
    'howItWorks.step1.bookCall': 'Boka ett videovägledningssamtal',
    'howItWorks.step2.title': 'Skölj',
    'howItWorks.step2.short': 'Endast rent vatten • Inget schampo eller balsam • Låt lufttorka naturligt',
    'howItWorks.step2.intro': 'Skölj endast med vatten, ta ett helt bad. Se till att det är 100% ur håret',
    'howItWorks.step2.d1': 'Skölj endast med vatten, ta ett helt bad. Se till att det är 100% ur håret',
    'howItWorks.step2.d2': 'Hårtyp 1A - 3B låt håret LUFTTORKA helt',
    'howItWorks.step2.d3': '3C - 4C gör en fläta och låt den lufttorka så',
    'howItWorks.step2.d4': 'Använd inga oljor eller krämer efteråt. Även om håret känns torrt efteråt',
    'howItWorks.step3.title': 'Underhåll',
    'howItWorks.step3.short': 'Första tvätten efter 4-7 dagar (endast mask) • Använd sulfatfria produkter • Njut av friskare hår i månader',
    'howItWorks.step3.intro': 'Efter 4-7 dagar kan du tvätta håret igen men endast med en hårmask',
    'howItWorks.step3.d1': 'Efter 4-7 dagar kan du tvätta håret igen men endast med en hårmask',
    'howItWorks.step3.d2': '(sulfatfri är vår rekommendation)',
    'howItWorks.step3.d3': 'Och om du har chansen att prova den jag har. Se till att den stannar i håret 1-2 timmar, skölj sedan ur',
    'howItWorks.step3.d4': 'Nu kan du använda oljor och även styla håret med fön',
    'howItWorks.step3.d5': 'Tredje tvätten?',
    'howItWorks.step3.d6': 'Du kan använda schampo och balsam',
    'howItWorks.step3.d7': 'Jag rekommenderar sulfatfritt',
    
    // Comparison Section
    'comparison.subtitle': 'Inte bara ännu en keratinbehandling - ett revolutionerande sätt att ta hand om håret',
    'comparison.ourTreatment': 'Vår Ekologiska Behandling',
    'comparison.trad.straightens': 'Rätar ut & plattar till håret',
    'comparison.ours.maintains': 'Bevarar naturlig textur',
    'comparison.trad.heat': 'Kräver värme & plattång',
    'comparison.ours.noHeat': 'Ingen värme behövs',
    'comparison.trad.formaldehyde': 'Innehåller formaldehyd',
    'comparison.ours.organic': '100% ekologisk formel',
    'comparison.trad.damages': 'Skadar lockmönstret',
    'comparison.ours.enhances': 'Förbättrar lockdefinitionen',
    'comparison.trad.notSafe': 'Inte säkert vid graviditet',
    'comparison.ours.safe': 'Säkert för graviditet & barn',
    'comparison.trad.demarcation': 'Hård demarkationslinje',
    'comparison.ours.seamless': 'Naturlig, sömlös utväxt',
    'comparison.trad.drier': 'Håret blir torrare över tid',
    'comparison.ours.improves': 'Progressiv förbättring',
    
    // About Section
    'about.discoverSubtitle': 'Upptäck passionen och engagemanget bakom Quality Hair',
    'about.tapInstruction': 'Klicka på varje kort för att läsa hela berättelsen',
    'about.readMore': 'Tryck för att läsa mer...',
    'about.journey.title': 'MIN RESA',
    'about.journey.text': 'Quality Hair började från min egen kamp med skadat, livlöst hår.\n\nI flera år använde jag hårfärger som torkade ut mitt hår. Jag var tvungen att glömma hårtillväxt.\n\nJag provade allt som fanns — inget fungerade.\n\nSen en dag hittade jag en keratinprodukt på en marknad som förändrade allt.\n\nEfter bara 7 månader blev mitt hår friskt, längre och lättare att hantera.\n\nJag lyckades övertyga min frisör att sälja produkten.\n\nEtt år senare gick hon med på det.\n\nJag började presentera behandlingen för vänner, familjemedlemmar och till och med främlingar jag mötte.\nJag utförde den på dem, och när de kom tillbaka för en andra behandling ringde det en klocka i mitt huvud.\n\nJag fick en kundbas som spred sig ganska snabbt.\n\nDet som började som en hobby tog mig med storm.\nJag ville bevisa att min behandling var annorlunda — ingen värme, inga hårda kemikalier, bara riktiga resultat. Och när mina kunder började komma tillbaka månader senare visste jag att jag hade något speciellt.',
    'about.creator.title': 'SKAPAREN',
    'about.creator.text': 'Jag byggde hela denna verksamhet själv.\nIngen finansiering. Inga investerare. Inget team.\nJag valde länderna. Jag gjorde marknadsföringen. Jag hanterade bokningar/depositioner.\nJag träffade kunder världen över.\nJag gjorde jobbet.\nDet här är mer än affärer –\n\nIdag har jag nått en punkt där efterfrågan är så hög,\natt flyga som jag gör inte längre är hållbart',
    'about.mission.title': 'VÅRT UPPDRAG',
    'about.mission.text': 'Jag säger alltid: bra hår definieras av hälsa, inte textur.\nMin behandling fungerar för barn, för gravida kvinnor och för alla som vill älska sitt hår utan att förändra det.\nDen ger fukt, minskar brott och återställer lockar — allt utan värme eller skador.\nI slutändan vill jag påminna kvinnor om att skönhet inte betyder att räta ut sin identitet. Det betyder att ta hand om det som redan är du.',
    'about.stats.customers': 'Nöjda Kunder',
    'about.stats.natural': 'Naturliga Ingredienser',
    'about.stats.experience': 'Års Erfarenhet',
    
    // Results Gallery Section
    'results.title': 'Före & Efter Transformationer',
    'results.subtitle': 'Se de otroliga resultaten våra kunder har uppnått med våra ekologiska keratinbehandlingar. Naturliga lockar förbättrade, inte förändrade.',
    'results.before': 'Före',
    'results.after': 'Resultat',
    
    // Footer Section
    'footer.learnMore': 'Läs Mer',
    'footer.howItWorks': 'Hur Det Fungerar',
    'footer.pricing': 'Priser',
    'footer.faq': 'FAQ',
    'footer.testimonials': 'Omdömen',
    'footer.benefits': 'Fördelar',
    'footer.compareTreatments': 'Jämför Behandlingar',
    'footer.ourStory': 'Vår Berättelse',
    'footer.resultsGallery': 'Resultatgalleri',
    'footer.contactWhatsApp': 'Kontakta via WhatsApp',
    'footer.emailUs': 'Maila Oss',
    'footer.bookConsultation': 'Boka Konsultation',
    'footer.instagram': 'Instagram',
    'footer.tiktok': 'TikTok',
    'footer.snapchat': 'Snapchat',
    'footer.organicCertified': '✓ 100% Ekologiskt Certifierat',
    'footer.safePregnancy': '✓ Säkert vid Graviditet',
    'footer.noHeatDamage': '✓ Inga Värmeskador',
    'footer.privacyPolicy': 'Integritetspolicy',
    'footer.termsOfService': 'Användarvillkor',
    
    // Final CTA
    'final.getRecommendation': 'Få Personlig Rekommendation',
    'final.viewAllPricing': 'Se Alla Priser',
    'final.limitedSupply': 'Begränsat månadslager tillgängligt.',
  },
  so: {
    // Header
    'header.cart': 'Gaariga',
    'header.language': 'Luuqad',
    
    // Navigation
    'nav.home': 'Guriga',
    'nav.benefits': "Faa'iidooyinka",
    'nav.product': 'Daawaynta',
    'nav.influencers': 'Saameeyayaal',
    'nav.tutorials': 'Tilmaamo',
    'nav.pricing': 'Qiimaha',
    'nav.faq': "Su'aalaha",
    
    // Hero
    'hero.badge': 'QADDAR BISHA XADDIDAN • ALAAB DABIICI AH',
    'hero.title': 'Timahaaga, La Hagaajiyey Xalal Gaarka Ah',
    'hero.subtitle': 'Ku raaxayso falanqaynta timaha ee AI-powered oo ay la socdaan hagida khibradda. Hel alaab dabiici ah oo loo qoondeeyey qaab-dhismeedkaaga timaha.',
    'hero.cta': 'Bilow Beddelkaaga',
    'hero.viewPricing': 'Arag Qiimaha',
    
    // Trust Indicators
    'trust.safePregnancy': 'Badbaado Uurka',
    'trust.organic': '100% Dabiici',
    'trust.noHeat': 'Kuleyl Looma Baahna',
    'trust.lasts': 'Waxay Raagtaa 3-6 Bilood',
    
    // Problem/Solution
    'problem.title': 'Sababta Keratin Caadiga ah U Guuldareysato',
    'problem.subtitle': 'Dhibaatada Daawaynta Caadiga ah',
    'problem.text1': 'Waxaan dhammaanteen ku heshiinaa inay qurux badan tahay bilowga. Todobaadyo ka dib, waxaad bilaabaysaa inaad lumiso timaha sababtoo ah daawayntu waxay timahaaga ka dhigtay toos. Maxaa yeelay timahaagu wuxuu isku dayaya inuu dib ugu laabmo.',
    'problem.text2': 'Ka dib 2-3 bilood, waxaad haysataa 2 qaab-dhismeed oo kala duwan. Qaar waxay xitaa arkaan timaha cusub ee koraya inuu leeyahay qaab-dhismeed engeg. Keratin caadiga ah wuxuu u baahan yahay kuleyl, lagumana talinayo uurka ama carruurta.',
    'solution.title': 'Xalka Quality Hair',
    'solution.subtitle': 'Keratin Dabiici Ah Oo La Shaqeeya Qaloocaadkaaga',
    'solution.text': 'Daawayntayadu waxay galataa timaha adiga oo aan jebin xidhiidhka. Qaloocaadkaagu wuu joogaa - waxay noqdaan caafimaad badan, cad, oo la maareeyo. Formaldehyde maleh, dhaawac kuleyl maleh, ammaan oo dhan.',
    
    // Pricing
    'pricing.title': 'Dooro Cabbirkaaga Daawaynta',
    'pricing.subtitle': 'Qiimaha wuxuu ku salaysan yahay dhererka timaha iyo qalafka',
    'pricing.addToCart': 'Ku Dar Gaariga',
    'pricing.popular': 'Ugu Caansan',
    'pricing.short': 'Timo Gaaban',
    'pricing.medium': 'Timo Dhexdhexaad',
    'pricing.long': 'Timo Dheer',
    'pricing.extraLong': 'Aad U Dheer',
    'pricing.consultation': 'Ma Hubin? Ballan La Tashi',
    'pricing.consultationDesc': 'Hel talo shaqsi ah khubarada timahayaga',
    'pricing.bookCall': 'Ballan Bilaash',
    
    // How It Works
    'steps.title': 'Safarkaaga Timaha Wanaagsan',
    'steps.step1.title': 'Dooro Nooca Timaha',
    'steps.step1.desc': 'Noo sheeg timahaaga - qallooc, toosan, jeexan, ama afro',
    'steps.step2.title': 'Soo Rar Sawirrada',
    'steps.step2.desc': 'Wadaag sawiro cad si lataliyayaashayada ay u fahmaan baahiyaha gaarka ah ee timahaaga',
    'steps.step3.title': 'Hel Alaabta',
    'steps.step3.desc': 'Hel talo la soo xulay oo leh tilmaamo isticmaal oo faahfaahsan',
    
    // Benefits
    'benefits.title': 'Maxay U Doorataa Quality Hair?',
    'benefits.maintains': 'Waxay Ilaalintaa Qaabka Qalooca',
    'benefits.maintainsDesc': 'Qaloocaadkaaga dabiiciga ah way jiraan - oo kaliya caafimaad badan oo cad',
    'benefits.organic': 'Qaab 100% Dabiici Ah',
    'benefits.organicDesc': 'Formaldehyde maleh, kimiko adag maleh - ammaan uurka iyo carruurta',
    'benefits.noHeat': 'Kuleyl Looma Baahna',
    'benefits.noHeatDesc': 'Si ka duwan keratin caadiga ah, flat iron ama blow dryer looma baahna',
    'benefits.lasting': 'Natiijooyin Raagaya',
    'benefits.lastingDesc': '3-6 bilood oo timo qurux badan, la maareeyo',
    
    // Comparison
    'comparison.title': 'Sideen U Isbarbardhignaa',
    'comparison.us': 'Quality Hair',
    'comparison.traditional': 'Keratin Caadiga ah',
    'comparison.maintainsCurls': 'Waxay Ilaalintaa Qaloocaadka',
    'comparison.chemicalFree': 'Kimiko Lacag',
    'comparison.pregnancySafe': 'Ammaan Uurka',
    'comparison.noHeat': 'Kuleyl Looma Baahna',
    
    // Social Proof
    'social.title': 'Lagu Soo Bandhigay Saameeyayaasha Ugu Sarreeya',
    'social.subtitle': 'Lagu kalsoonaaday kumanaan oo lagu ammaanay codadka ugu weyn ee warbaahinta bulshada',
    'social.followers': 'Raacayaal',
    'social.watch': 'Daaw Muuqaalka',
    'social.stats.customers': 'Macaamiil Faraxsan',
    'social.stats.influencers': 'Saameeyayaal Wadaag',
    'social.stats.views': 'Daawasho Warbaahinta',
    
    // Testimonials
    'testimonials.title': 'Natiijooyin Dhab ah oo Dad Dhab ah',
    
    // FAQ
    'faq.title': "Su'aalaha Inta Badan La Weydiiyo",
    'faq.all': 'Dhammaan',
    'faq.treatment': 'Daawaynta',
    'faq.safety': 'Badbaado',
    'faq.aftercare': 'Daryeelka Kadib',
    'faq.ordering': 'Dalabka',
    
    // About
    'about.title': 'Sheekadayada',
    'about.subtitle': 'Waxaa aasaasay qof fahmaya safarkaaga timaha',
    
    // Final CTA
    'final.title': 'Diyaar U Tahay Inaad Beddesho Timahaaga?',
    'final.subtitle': 'Ku biir kumanaan soo ogaaday habka daryeelka timaha ee dabiiciga ah. Qaddar xaddidan oo la heli karo bisha.',
    'final.cta': 'Bilow Safarkaaga Hadda',
    
    // Footer
    'footer.rights': 'Dhammaan xuquuqda way dhowran yihiin',
    'footer.quickLinks': 'Linkiyada Degdegga',
    'footer.support': 'Taageero',
    'footer.connect': 'Xiriir',
    
    // Hair Types
    'hairtype.curly': 'Qallooc',
    'hairtype.straight': 'Toosan',
    'hairtype.frizzy': 'Jeexan',
    'hairtype.afro': 'Afro',
    
    // Common
    'common.learnMore': 'Wax Badan Baro',
    'common.getStarted': 'Bilow',
    'common.viewAll': 'Arag Dhammaan',
    'common.close': 'Xir',
    
    // Benefits Section (expanded)
    'benefits.subtitle': 'Ku raaxayso isbeddelka timahaagu mudan yahay',
    'benefits.qualityHair': 'Quality Hair',
    'benefits.qualityHairDesc': 'Gaar timo caafimaad qaba, dhalaalaya oo lagu qeexay awoodooda iyo xooggooda',
    'benefits.maintainsCurl': 'Waxay Ilaalintaa Qaabkaaga Qalooca',
    'benefits.maintainsCurlDesc': 'Hayso qaab-dhismeedkaaga dabiiciga ah adiga oo wanaajinaya qeexitaanka iyo qooynaanta',
    'benefits.manageability': 'La Maareeyn Karo',
    'benefits.manageabilityDesc': 'Shanlo fudud, styling sahlan, iyo daryeel maalin-walba oo fudud',
    'benefits.lessBreakage': 'Dhicid Timo Yar & Jajab',
    'benefits.lessBreakageDesc': 'Xoogsii gudaha si aad u yaraysid dhicidda oo aad ka ilaalisid dhaawaca',
    'benefits.growthSupport': 'Taageero Korriinka',
    'benefits.growthSupportDesc': 'Abuur aasaaska saxda ah ee korriin timo caafimaad qaba oo joogta ah',
    'benefits.heatFree': 'Daawayn Kuleyl La\'aan',
    'benefits.heatFreeDesc': 'Kuleyl maleh, plattänger maleh, dhaawac maleh — oo kaliya isku-dheelitir dabiici ah',
    
    // Pricing Section (expanded)
    'pricing.mostPopular': 'UGU CAANSAN',
    'pricing.minimal': 'Minimal',
    'pricing.minimalDesc': 'Timo fiican, gaaban - Ka hooseeya dhererka garbaha',
    'pricing.moderate': 'Dhexdhexaad',
    'pricing.moderateDesc': 'Qalin dhexdhexaad - Timo garbo dheer',
    'pricing.full': 'Buuxa',
    'pricing.fullDesc': 'Timo qalafsan, dheer - Ka hooseeya garbaha/ka sarreeya laabta',
    'pricing.maximum': 'Maximum',
    'pricing.maximumDesc': 'Timo aad u qalafsan - Ka hooseeya heerka laabta',
    'pricing.feature.completeKit': 'Kit dhamaystiran',
    'pricing.feature.applicationGuide': 'Hagaha codsiga',
    'pricing.feature.videoSupport': 'Taageero fiidiyow',
    'pricing.feature.lasts': 'Waxay raagtaa 3-6 bilood',
    'pricing.addons': 'Alaab Dheeraad',
    'pricing.bundle': 'Maaskada Timaha + Serum Xirmada',
    'pricing.bundleDesc': 'Isku-dar labadaba si daryeel kadib ugu fiican',
    'pricing.maskOnly': 'Maaskada Timaha Oo Kaliya',
    'pricing.maskOnlyDesc': 'Daawayn qooyso oo mug leh',
    'pricing.serumOnly': 'Serum Timaha Oo Kaliya',
    'pricing.serumOnlyDesc': 'Dhalaal maalinle ah iyo ilaalin',
    'pricing.notSure': 'Ma Hubin Cabbirka?',
    'pricing.consultationText': 'Ballan la tashi fiidiyow 10-daqiiqo ah €10. Waxaan qiimeynaa timahaaga waxaana ku talinaa qaddarka saxda ah. Haddii aad wax ka iibsato inta lagu jiro wicitaanka, €10 waxaa lagu tiriyaa dalabkaaga. Haddii kale, khidmadda la-tashigu dib looma celiyo.',
    'pricing.bookConsultation': 'Ballan La-tashi (€10)',
    'pricing.sessionTitle': 'Fadhiga 30-Daqiiqada',
    'pricing.sessionDesc': 'Wicitaan fiidiyow shakhsi ah oo ay la jirto khabiirka timahayaga',
    'pricing.planTitle': 'Qorshaha Shakhsiga',
    'pricing.planDesc': 'Talooyin daawayn oo loo qoondeeyey timahaaga',
    'pricing.creditTitle': 'Deyn Iibsiga',
    'pricing.creditDesc': 'Khidmadda la-tashiga €10 waxaa lagu codsadaa dalabkaaga',
    
    // FAQ Section (expanded)
    'faq.subtitle': "Wax kasta oo aad u baahan tahay inaad ka ogaato daawayntayada keratin-ka dabiiciga ah",
    'faq.allQuestions': "Su'aalaha Dhammaan",
    'faq.stillQuestions': "Weli ma haysataa su'aalo?",
    'faq.contactSupport': 'La xiriir kooxdayada taageerada →',
    'faq.q1': 'Tani ma toosi doontaa timahayga?',
    'faq.a1': 'MAYA - taas weeye waxaa naga gaar ah. Qaloocaadkaagu way joogaan, waxay noqdaan oo kaliya caafimaad badan, cad, oo la maareeyo. Todobaadyadii ugu horreeyay, qaloocaadku waxay u muuqdaan mid debecsan sababtoo ah qoysnaanta oo kordhay, laakiin waxay ku noqdaan qaabkooda dabiiciga ah.',
    'faq.q2': 'Intee in le\'eg ayay daawayntu socotaa?',
    'faq.a2': '3-6 bilood iyadoo ku xiran noocaaga timaha iyo daryeelka kadib. Si ka duwan daawaynaha dhaqameed, ma jirto khad xad adag - si dabiici ah ayay u lumaysaa.',
    'faq.q3': 'Sidee buu tani uga duwan yahay daawaynaha keratin ee salonka?',
    'faq.a3': 'Salonka keratin caadiga ah wuxuu isticmaalaa kuleyl iyo kimiko si uu u burburo xidhiidhka timaha oo uu toosiyo. Qaabkeena dabiiciga ah wuxuu la shaqeeyaa qaabka qaloocaadkaaga dabiiciga ah, wuxuu ku daraa xoog wuxuuna yareeya frizz adiga oo aan beddelin qaab-dhismeedkaaga.',
    'faq.q4': 'Ma ammaan bay u tahay carruurta iyo uurka?',
    'faq.a4': 'Haa! 100% dabiici ah oo ay ku jiraan molekyulooyin si dabiici ah ugu jira timaha. Formaldehyde maleh, kimiko waxyeelo leh maleh. Ammaan dhammaan da\'yarta iyo uurka.',
    'faq.q5': 'Walxaha maxay yihiin daawaynta?',
    'faq.a5': 'Qaabkeena wuxuu ka kooban yahay borotiin keratin dabiici ah, amino acids dabiici ah, saliidda argan, iyo alaab balsam oo dhir ku salaysan. Sifir formaldehyde, parabens, ama sulfates.',
    'faq.q6': 'Miyaan u isticmaali karaa timo la midabay?',
    'faq.a6': 'Gebi ahaanba! Daawayntayadu waa ammaan dhammaan noocyada timaha oo ay ku jiraan kuwo midab leh, slingado leh, iyo timo kimiko lagu daaweeyay. Waxay xitaa kaa caawin kartaa inaad dheerayso dhalaalaadka midabkaaga.',
    'faq.q7': 'Intee jeer ayaan ku celi karaa daawaynta?',
    'faq.a7': 'Sug 3-4 bilood u dhexeeya daawaynaha (mararka qaarkood 5-6 bilood). Timahaagu waxay kuu sheegi doonaan goortay u baahan yihiin wax badan - borotiin badan looma talinayo.',
    'faq.q8': 'Shampoo noocee ah ayaan isticmaali daawaynta kadib?',
    'faq.a8': 'Isticmaal shampoo sulfate-free ah si aad u kordhiso natiijooyinka. Waxaan ku talineynaa inaad sugto 48 saacadood ka hor dhaqidda koowaad. Shampoo kasta oo qabow, sulfate-free ah wuu shaqeeyaa si fiican.',
    'faq.q9': 'Miyaan dabaali karaa ama jirdhaqdo kadib daawaynta?',
    'faq.a9': "Sug 48-72 saacadood ka hor dabaalka ama dhidid culus. Taas kadib, waad diyaar tahay! Biyo nadiif ah ku maydh timaha kadib dabaalka biyaha chlorine ama milixda leh.",
    'faq.q10': 'Maxaa ku jira iibkayga?',
    'faq.a10': '• Daawayntaada keratin dabiiciga ah (cabbirka la doortay)\n• Hagaha codsiga oo faahfaahsan\n• Helitaanka fiidiyowyada tababarka\n• Taageero iimayl\n• Damaanad qanacsanaanshaha 30-maalmood',
    'faq.q11': 'Sideen u doorataa cabbirka saxda ah?',
    'faq.a11': 'Isticmaal qalabkayaga Falanqaynta Timaha si aad u hesho talo shakhsi ah. Guud ahaan: Minimal (timo gaaban/fiican), Moderat (dhererka garbaha), Full (dheer/qalafsan), Maximum (aad u dheer/aad u qalafsan).',
    'faq.q12': 'Maxay tahay siyaasaddinna celinta?',
    'faq.a12': 'Waxaan bixinaa damaanad qanacsanaansho 30-maalmood ah. Haddii aadan ku faraxsanayn natiijooyinkaaga, nala soo xiriir si aad u hesho lacag celinta oo buuxa ama beddelan. Alaabaha aan la furin waa la soo celin karaa 60 maalmood gudahood.',
    
    // How It Works Section
    'howItWorks.title': 'Seddex Tallaabo Oo Fudud',
    'howItWorks.subtitle': 'Habka codsiga fudud - salon looma baahna',
    'howItWorks.clickInstruction': 'Guji tallaabo kasta si aad u hesho hagitaan faahfaahsan (taabo mobilka)',
    'howItWorks.footer': '*Hagaha codsiga oo buuxa ayaa la socda iibka',
    'howItWorks.step1.title': 'Codso',
    'howItWorks.step1.short': 'Ku maydh shampoo oo kaliya • Si buuxda u qalaji • Codso qaybta qaybta',
    'howItWorks.step1.intro': 'Waxaad awoodi kartaa inaad ballansato 30 daqiiqo wicitaan fiidiyow hagitaan ama akhri qoraalka codsiga',
    'howItWorks.step1.d1': 'Tuwaalo ha diyaarso',
    'howItWorks.step1.d2': '2-3 shanlo timo oo cabbir kala duwan & galoofyo',
    'howItWorks.step1.d3': 'Ku maydh timaha shampoo oo kaliya',
    'howItWorks.step1.d4': 'Ka hor inta aan la codsan timaha waa inay ahaadaan 100% qalalan oo aan lahayn raad saliid. Xitaa sug 1 maalin oo kale si aad u hubiso',
    'howItWorks.step1.d5': 'Nooca timaha 1A - 3B timahaagu waxay hawo ku qalaji karaan ka hor codsiga hubi inaad si sax ah u shantaysid',
    'howItWorks.step1.d6': "Nooca timaha 3C-4C waxaad awoodi kartaa inaad timahaaga ku foonaysid si toosan haddii ay fududahay inaad sidaas u maamusho",
    'howItWorks.step1.d7': 'U kala qaybi timaha 10-12 lakab. Dhinaca bidix 5-6 lakab iyo dhinaca midig sidoo kale. Ka bilow hoosta',
    'howItWorks.step1.d8': 'Marka hore si sax ah u shantaysi',
    'howItWorks.step1.d9': 'Codso qaddar yar oo daawayn ah oo shanlo yar ku shantaysi 5-6 jeer ilaa aad dareento inay fududahay in la shantaysho daawayntuna si sax ah u gashay',
    'howItWorks.step1.d10': 'Hadda waxaad awoodi kartaa inaad mar kale ku codsatid borotiin badan dhinacaas',
    'howItWorks.step1.d11': 'Oo u gudub dhinaca xiga',
    'howItWorks.step1.d12': 'Hubi inaadan daawaynta ku codsan dubka madaxaaga ama ku xoqo dubka madaxaaga ama timaha yaryarkaaga. Laakiin isku day inaad u dhowaato inta aad awoodid',
    'howItWorks.step1.d13': 'Waqtigaagu wuxuu ka bilaabmaa markii aad daawaynta oo dhan ku codsatay timahaaga',
    'howItWorks.step1.d14': 'Nooca timaha 1A - 3A - waxay ku hayn karaan 60-80 daqiiqo',
    'howItWorks.step1.d15': 'Nooca timaha 3B-4A - waxay ku hayn karaan 2 saacadood',
    'howItWorks.step1.d16': '4B-4C waxay ku hayn karaan 2 saacadood iyo 30 daqiiqo',
    'howItWorks.step1.d17': 'Markaad haysato 20 daqiiqo ka hor intaadan maydhinna timaha - waxaad awoodi kartaa inaad garaacdo dubka madaxaaga si ay u gaarto dubka madaxaaga oo ku codsato timaha yaryarkaaga',
    'howItWorks.step1.d18': 'Haddii ay dareento cuncun ha xoqin. Way dhammaan doontaa. (Sababta cuncunka waa maqaar qalalan)',
    'howItWorks.step1.helpText': 'Ma u baahan tahay caawimaad codsiga?',
    'howItWorks.step1.bookCall': 'Ballanso wicitaan hagitaan fiidiyow ah',
    'howItWorks.step2.title': 'Maydh',
    'howItWorks.step2.short': 'Biyo nadiif ah oo kaliya • Shampoo ama conditioner maleh • Si dabiici ah hawo ku qalaji',
    'howItWorks.step2.intro': 'Biyo oo kaliya ku maydh qaado qubaysi buuxa. Hubi inay 100% ka baxday timaha',
    'howItWorks.step2.d1': 'Biyo oo kaliya ku maydh qaado qubaysi buuxa. Hubi inay 100% ka baxday timaha',
    'howItWorks.step2.d2': 'Nooca timaha 1A - 3B u daa timahaaga inay si buuxa u HAWO QALAJIYAAN',
    'howItWorks.step2.d3': '3C - 4C samee hal tolaay oo u daa inuu sidaas hawo ku qalaljiyo',
    'howItWorks.step2.d4': 'Ha isticmaalin wax saliid ah ama kariimo kadib. Xitaa haddii timahaagu dareemaan qalal kadib',
    'howItWorks.step3.title': 'Ilaali',
    'howItWorks.step3.short': 'Maydhitaanka koowaad kadib 4-7 maalmood (maaskada oo kaliya) • Isticmaal alaab sulfate-free ah • Ku raaxayso timo caafimaad qaba bilooyin',
    'howItWorks.step3.intro': 'Kadib 4-7 maalmood waxaad awoodi kartaa inaad mar kale maydhato timahaaga laakiin maaskada timaha oo kaliya',
    'howItWorks.step3.d1': 'Kadib 4-7 maalmood waxaad awoodi kartaa inaad mar kale maydhato timahaaga laakiin maaskada timaha oo kaliya',
    'howItWorks.step3.d2': '(sulphate free ayaa talo ahaan)',
    'howItWorks.step3.d3': 'Haddii aad fursad u hesho inaad tijaabiso tan aan haysto. Hubi inay ku jirto timahaaga 1-2 saacadood kadibna maydh',
    'howItWorks.step3.d4': 'Hadda waxaad awoodi kartaa inaad isticmaasho saliidaha iyo sidoo kale timahaaga foon ku qurxiso',
    'howItWorks.step3.d5': 'Maydhitaanka saddexaad?',
    'howItWorks.step3.d6': 'Waxaad isticmaali kartaa shampoo iyo conditioner',
    'howItWorks.step3.d7': 'Waxaan ku talinayaa sulphate free',
    
    // Comparison Section
    'comparison.subtitle': 'Ma ahan keratin daawayn kale oo kaliya - hab cusub oo daryeelka timaha',
    'comparison.ourTreatment': 'Daawayntayada Dabiiciga Ah',
    'comparison.trad.straightens': 'Waxay toosisaa & siman timaha',
    'comparison.ours.maintains': 'Waxay ilaalintaa qaab-dhismeedka dabiiciga ah',
    'comparison.trad.heat': 'Waxay u baahan tahay kuleyl & plattång',
    'comparison.ours.noHeat': 'Kuleyl looma baahna',
    'comparison.trad.formaldehyde': 'Waxay ka kooban tahay formaldehyde',
    'comparison.ours.organic': 'Qaab 100% dabiici ah',
    'comparison.trad.damages': 'Waxay dhaawacaysaa qaabka qalooca',
    'comparison.ours.enhances': 'Waxay wanaajisaa qeexitaanka qalooca',
    'comparison.trad.notSafe': 'Ma ammaan uurka',
    'comparison.ours.safe': 'Ammaan uurka & carruurta',
    'comparison.trad.demarcation': 'Khad xad adag',
    'comparison.ours.seamless': 'Korriinka dabiiciga ah, isku dhafan',
    'comparison.trad.drier': 'Timaha waxay noqdaan qalalan waqti ka dib',
    'comparison.ours.improves': 'Horumar tartiib tartiib ah',
    
    // About Section
    'about.discoverSubtitle': 'Ogaw jacaylka iyo dedaalka ka dambeeya Quality Hair',
    'about.tapInstruction': 'Taabo kaadhka si aad u akhrisato sheekada oo dhan',
    'about.readMore': 'Taabo si aad wax badan u akhrisato...',
    'about.journey.title': 'SAFARKAYGA',
    'about.journey.text': "Quality Hair waxay ka bilaabatay dagaalkayga timaha dhaawacay, nolosha la'aanta.\n\nSannado badan, waxaan isticmaalay midabyo timo ah oo qalaliyay timahayga. Waxaan ku qasbanaaday inaan iloobo korriinka timaha.\n\nWax kasta oo meesha ku yaal waan tijaabiyay — waxba ma shaqaynin.\n\nMaalin baa waxaan ka helay suuq alaab keratin ah oo wax walba beddeshay.\n\nKadib oo kaliya 7 bilood, timahaygu waxay noqdeen caafimaad qaba, dheer, oo sahlan in la maareeyo.\n\nWaxaan ku guuleystay inaan u qanciyo firiisarkeeyga inuu iibiyo alaabta.\n\nHal sano kadib, way ogolaatay.\n\nWaxaan bilaabay inaan soo bandhigo daawaynta saaxiibbo, xubnaha qoyska, iyo xitaa shisheeyayaal aan la kulmay.\nWaxaan ku sameeyay iyaga, markay u soo noqdeen daawayn labaad, dawash ayaa maskaxdayda ka dhacday.\n\nWaxaan helay saldhig macaamiil ah oo si degdeg ah u faafay.\n\nWaxa uu bilaabay xiiso ahaan wuxuu igu qaatay duufaan.\nWaxaan rabay inaan caddeeyo in daawayntaydu ay kala duwantahay — kuleyl maleh, kimiko adag maleh, oo kaliya natiijooyin dhabta ah. Markii macaamiishaydu bilaabeen inay soo noqdaan bilooyin kadib, waxaan ogaaday inaan wax gaar ah haysto.",
    'about.creator.title': 'ABUURAHA',
    'about.creator.text': "Dhismaha oo dhan waxaan isku dhisay.\nMaal maleh. Maalgashadayaal maleh. Koox maleh.\nAnigaa doortay dalalka. Anigaa sameeyay suuq-geynta. Anigaa maareeyay ballannada/lacagta.\nMacaamiil adduunka oo dhan ayaan la kulmay.\nAnigaa sameeyay shaqada.\nTani waa wax ka badan ganacsi –\n\nMaanta, waxaan gaaray heer uu baahidu aad u sarreeyo,\nduulimaadka aan ku jiro ee sidaan oo kale ah hadda ma aha mid waara",
    'about.mission.title': 'HADAFKEENA',
    'about.mission.text': "Mar walba waxaan leeyahay: timo wanaagsan waxaa lagu qeexaa caafimaad, ma aha qaab-dhismeed.\nDaawayntaydu waxay u shaqeysaa carruurta, haweenka uurka leh, iyo qof kasta oo raba inuu jeclaado timihiisa iyagoo aan beddelin.\nWaxay keentaa qoysnaanta, waxay yaraynaysaa jajabka, waxayna soo celisaa qaloocaadka — oo dhan kuleyl ama dhaawac la'aan.\nDhammaadka, waxaan rabaa inaan haweenka xasuusiyo in quruxdu aysan macnaheedu ahayn inaad toosiso aqoonsigaaga. Macnaheedu waa inaad daryeesho waxa mar horeba ku ah adiga.",
    'about.stats.customers': 'Macaamiil Faraxsan',
    'about.stats.natural': 'Walxaha Dabiiciga ah',
    'about.stats.experience': 'Sannado Khibrad',
    
    // Results Gallery Section
    'results.title': 'Hore & Kadib Isbeddelada',
    'results.subtitle': 'Arag natiijooyinka cajiibka ah ee macaamiishayadaagu gaareen daawayntayada keratin-ka dabiiciga ah. Qaloocaadka dabiiciga ah waa la wanaajiyay, ma beddelin.',
    'results.before': 'Hore',
    'results.after': 'Natiijooyinka',
    
    // Footer Section
    'footer.learnMore': 'Wax Badan Baro',
    'footer.howItWorks': 'Sida U Shaqeysa',
    'footer.pricing': 'Qiimaha',
    'footer.faq': "Su'aalaha",
    'footer.testimonials': 'Marag-furka',
    'footer.benefits': "Faa'iidooyinka",
    'footer.compareTreatments': 'Isbarbardhig Daawaynta',
    'footer.ourStory': 'Sheekadeena',
    'footer.resultsGallery': 'Sawirrada Natiijooyinka',
    'footer.contactWhatsApp': 'La xiriir WhatsApp',
    'footer.emailUs': 'Noo Iimayl',
    'footer.bookConsultation': 'Ballan La-tashi',
    'footer.instagram': 'Instagram',
    'footer.tiktok': 'TikTok',
    'footer.snapchat': 'Snapchat',
    'footer.organicCertified': '✓ 100% Dabiici Shahaado leh',
    'footer.safePregnancy': '✓ Ammaan Uurka',
    'footer.noHeatDamage': '✓ Dhaawac Kuleyl Maleh',
    'footer.privacyPolicy': 'Siyaasadda Sirta',
    'footer.termsOfService': 'Shuruudaha Adeegga',
    
    // Final CTA
    'final.getRecommendation': 'Hel Talo Shakhsi Ah',
    'final.viewAllPricing': 'Arag Dhammaan Qiimaha',
    'final.limitedSupply': 'Qaddar bisha oo xaddidan ayaa la heli karaa.',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
